import { Node, Edge, MarkerType } from 'reactflow';

export type TemplateType = 'stakeholder' | 'systems' | 'network' | 'strategic' | null;

export interface Template {
  id: TemplateType;
  name: string;
  description: string;
  nodes: Node[];
  edges: Edge[];
}

const stakeholderTemplate: Template = {
  id: 'stakeholder',
  name: 'Stakeholder Mapping',
  description: 'Directed network showing influence and relationships between stakeholders',
  nodes: [
    {
      id: '1',
      type: 'default',
      position: { x: 400, y: 100 },
      data: { label: 'Executive Team' },
      style: {
        background: 'hsl(var(--primary))',
        color: 'white',
        border: '2px solid hsl(var(--primary-light))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '500',
      },
    },
    {
      id: '2',
      type: 'default',
      position: { x: 200, y: 250 },
      data: { label: 'Investors' },
      style: {
        background: 'hsl(var(--secondary))',
        color: 'white',
        border: '2px solid hsl(var(--secondary-light))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
    {
      id: '3',
      type: 'default',
      position: { x: 600, y: 250 },
      data: { label: 'Customers' },
      style: {
        background: 'hsl(var(--secondary))',
        color: 'white',
        border: '2px solid hsl(var(--secondary-light))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
    {
      id: '4',
      type: 'default',
      position: { x: 400, y: 400 },
      data: { label: 'Employees' },
      style: {
        background: 'hsl(var(--accent))',
        color: 'white',
        border: '2px solid hsl(var(--accent-light))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
  ],
  edges: [
    {
      id: 'e1-2',
      source: '1',
      target: '2',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--primary))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--primary))',
      },
      label: 'reports to',
    },
    {
      id: 'e1-3',
      source: '1',
      target: '3',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--primary))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--primary))',
      },
      label: 'serves',
    },
    {
      id: 'e1-4',
      source: '1',
      target: '4',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--primary))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--primary))',
      },
      label: 'manages',
    },
    {
      id: 'e2-1',
      source: '2',
      target: '1',
      type: 'smoothstep',
      style: { stroke: 'hsl(var(--border))', strokeWidth: 1.5 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--border))',
      },
      label: 'influences',
    },
  ],
};

const systemsTemplate: Template = {
  id: 'systems',
  name: 'Systems Thinking',
  description: 'Causal loop diagram showing feedback cycles and system dynamics',
  nodes: [
    {
      id: '1',
      type: 'default',
      position: { x: 300, y: 100 },
      data: { label: 'Product Quality' },
      style: {
        background: 'hsl(var(--primary))',
        color: 'white',
        border: '2px solid hsl(var(--primary-light))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
    {
      id: '2',
      type: 'default',
      position: { x: 600, y: 100 },
      data: { label: 'Customer Satisfaction' },
      style: {
        background: 'hsl(var(--secondary))',
        color: 'white',
        border: '2px solid hsl(var(--secondary-light))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
    {
      id: '3',
      type: 'default',
      position: { x: 600, y: 300 },
      data: { label: 'Sales Revenue' },
      style: {
        background: 'hsl(var(--accent))',
        color: 'white',
        border: '2px solid hsl(var(--accent-light))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
    {
      id: '4',
      type: 'default',
      position: { x: 300, y: 300 },
      data: { label: 'R&D Investment' },
      style: {
        background: 'hsl(var(--primary-light))',
        color: 'white',
        border: '2px solid hsl(var(--primary))',
        borderRadius: '12px',
        padding: '16px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
  ],
  edges: [
    {
      id: 'e1-2',
      source: '1',
      target: '2',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--primary))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--primary))',
      },
      label: '+',
    },
    {
      id: 'e2-3',
      source: '2',
      target: '3',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--secondary))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--secondary))',
      },
      label: '+',
    },
    {
      id: 'e3-4',
      source: '3',
      target: '4',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--accent))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--accent))',
      },
      label: '+',
    },
    {
      id: 'e4-1',
      source: '4',
      target: '1',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--primary-light))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--primary-light))',
      },
      label: '+',
    },
  ],
};

const networkTemplate: Template = {
  id: 'network',
  name: 'Network Analysis',
  description: 'Undirected network for social network analysis and community detection',
  nodes: [
    {
      id: '1',
      type: 'default',
      position: { x: 400, y: 200 },
      data: { label: 'Node A' },
      style: {
        background: 'hsl(var(--primary))',
        color: 'white',
        border: '2px solid hsl(var(--primary-light))',
        borderRadius: '50%',
        padding: '20px',
        fontSize: '14px',
        fontWeight: '300',
        width: '80px',
        height: '80px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
    },
    {
      id: '2',
      type: 'default',
      position: { x: 200, y: 300 },
      data: { label: 'Node B' },
      style: {
        background: 'hsl(var(--secondary))',
        color: 'white',
        border: '2px solid hsl(var(--secondary-light))',
        borderRadius: '50%',
        padding: '20px',
        fontSize: '14px',
        fontWeight: '300',
        width: '80px',
        height: '80px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
    },
    {
      id: '3',
      type: 'default',
      position: { x: 600, y: 300 },
      data: { label: 'Node C' },
      style: {
        background: 'hsl(var(--secondary))',
        color: 'white',
        border: '2px solid hsl(var(--secondary-light))',
        borderRadius: '50%',
        padding: '20px',
        fontSize: '14px',
        fontWeight: '300',
        width: '80px',
        height: '80px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
    },
    {
      id: '4',
      type: 'default',
      position: { x: 400, y: 420 },
      data: { label: 'Node D' },
      style: {
        background: 'hsl(var(--accent))',
        color: 'white',
        border: '2px solid hsl(var(--accent-light))',
        borderRadius: '50%',
        padding: '20px',
        fontSize: '14px',
        fontWeight: '300',
        width: '80px',
        height: '80px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
    },
  ],
  edges: [
    {
      id: 'e1-2',
      source: '1',
      target: '2',
      type: 'straight',
      style: { stroke: 'hsl(var(--border))', strokeWidth: 2 },
    },
    {
      id: 'e1-3',
      source: '1',
      target: '3',
      type: 'straight',
      style: { stroke: 'hsl(var(--border))', strokeWidth: 2 },
    },
    {
      id: 'e2-4',
      source: '2',
      target: '4',
      type: 'straight',
      style: { stroke: 'hsl(var(--border))', strokeWidth: 2 },
    },
    {
      id: 'e3-4',
      source: '3',
      target: '4',
      type: 'straight',
      style: { stroke: 'hsl(var(--border))', strokeWidth: 2 },
    },
    {
      id: 'e2-3',
      source: '2',
      target: '3',
      type: 'straight',
      style: { stroke: 'hsl(var(--border))', strokeWidth: 1 },
    },
  ],
};

const strategicTemplate: Template = {
  id: 'strategic',
  name: 'Strategic Planning',
  description: 'Hierarchical directed network for goals and initiatives',
  nodes: [
    {
      id: '1',
      type: 'default',
      position: { x: 400, y: 50 },
      data: { label: 'Vision' },
      style: {
        background: 'hsl(var(--primary))',
        color: 'white',
        border: '2px solid hsl(var(--primary-light))',
        borderRadius: '12px',
        padding: '16px 24px',
        fontSize: '15px',
        fontWeight: '500',
      },
    },
    {
      id: '2',
      type: 'default',
      position: { x: 200, y: 180 },
      data: { label: 'Goal 1' },
      style: {
        background: 'hsl(var(--secondary))',
        color: 'white',
        border: '2px solid hsl(var(--secondary-light))',
        borderRadius: '12px',
        padding: '14px 20px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
    {
      id: '3',
      type: 'default',
      position: { x: 600, y: 180 },
      data: { label: 'Goal 2' },
      style: {
        background: 'hsl(var(--secondary))',
        color: 'white',
        border: '2px solid hsl(var(--secondary-light))',
        borderRadius: '12px',
        padding: '14px 20px',
        fontSize: '14px',
        fontWeight: '300',
      },
    },
    {
      id: '4',
      type: 'default',
      position: { x: 100, y: 320 },
      data: { label: 'Initiative A' },
      style: {
        background: 'hsl(var(--accent))',
        color: 'white',
        border: '2px solid hsl(var(--accent-light))',
        borderRadius: '12px',
        padding: '12px 18px',
        fontSize: '13px',
        fontWeight: '300',
      },
    },
    {
      id: '5',
      type: 'default',
      position: { x: 300, y: 320 },
      data: { label: 'Initiative B' },
      style: {
        background: 'hsl(var(--accent))',
        color: 'white',
        border: '2px solid hsl(var(--accent-light))',
        borderRadius: '12px',
        padding: '12px 18px',
        fontSize: '13px',
        fontWeight: '300',
      },
    },
    {
      id: '6',
      type: 'default',
      position: { x: 700, y: 320 },
      data: { label: 'Initiative C' },
      style: {
        background: 'hsl(var(--accent))',
        color: 'white',
        border: '2px solid hsl(var(--accent-light))',
        borderRadius: '12px',
        padding: '12px 18px',
        fontSize: '13px',
        fontWeight: '300',
      },
    },
  ],
  edges: [
    {
      id: 'e1-2',
      source: '1',
      target: '2',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--primary))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--primary))',
      },
    },
    {
      id: 'e1-3',
      source: '1',
      target: '3',
      type: 'smoothstep',
      animated: true,
      style: { stroke: 'hsl(var(--primary))', strokeWidth: 2 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--primary))',
      },
    },
    {
      id: 'e2-4',
      source: '2',
      target: '4',
      type: 'smoothstep',
      style: { stroke: 'hsl(var(--secondary))', strokeWidth: 1.5 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--secondary))',
      },
    },
    {
      id: 'e2-5',
      source: '2',
      target: '5',
      type: 'smoothstep',
      style: { stroke: 'hsl(var(--secondary))', strokeWidth: 1.5 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--secondary))',
      },
    },
    {
      id: 'e3-6',
      source: '3',
      target: '6',
      type: 'smoothstep',
      style: { stroke: 'hsl(var(--secondary))', strokeWidth: 1.5 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: 'hsl(var(--secondary))',
      },
    },
  ],
};

export const templates: Record<string, Template> = {
  stakeholder: stakeholderTemplate,
  systems: systemsTemplate,
  network: networkTemplate,
  strategic: strategicTemplate,
};

export const getTemplate = (type: TemplateType): Template | null => {
  if (!type) return null;
  return templates[type] || null;
};
